[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npx vite build"]

[start]
cmd = "npm run migrate; npm run start"
